---
- name: Full basic setting server
  hosts: host_1
  become: yes

  vars_files:
    - variables_host_1.yaml

  tasks:
  - name: Update and upgrade all programms
    ansible.builtin.apt:
      update_cache: yes


  - name: Add new user
    ansible.builtin.user:
      name: "{{ create_user }}"
      create_home: true
      shell: /bin/bash

  - name: Make sure we have a sudo group
    ansible.builtin.group:
      name: sudo
      state: present
  - name: Give sudo for user
    ansible.builtin.user:
      name: "{{ create_user }}"
      state: present
      groups: sudo
      append: true

  - name: Add SSH key for user
    ansible.builtin.authorized_key:
      user: "{{ create_user }}"
      state: present
      key: "{{ SSH_key }}"

  - name: Installing utilities mc, htop, atop, ncdu
    ansible.builtin.apt:
      name:
        - mc
        - htop
        - atop
        - ncdu

  - name: Changing SSH-port
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^#Port 22'
      line: 'Port {{ ssh_port }}'

  - name: Disabling password autentification
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^#PasswordAuthentication yes'
      line: 'PasswordAuthentication no'
    notify: Restart SSH service



  handlers:
  - name: Restart SSH service
    systemd:
      name: ssh
      state: restarted
...
